[package]
name = "ringbuffer"
version = "0.1.0"
edition = "2018"
license = "LGPL-3.0"
description="Low level NSCLDAQ ring buffer access"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "0.6.2"